### ISSUE TITLE
this sim is bad

### ISSUE THREAD

**Issue by tacotacoweb** [touhourenren/TJAPlayer3-Develop-ReWrite#17]
**Describe the bug**
(バグについての説明を書いてください)

**To Reproduce**
(バグを引き起こすまでの手順を書いてください)

**Expected behavior**
(バグによって起こる動作)

**Screenshots**
(スクリーンショットを添付してください)

**Desktop (please complete the following information):**
(バグが起こったPC環境を書いてください)

**Additional context**
(追加情報を書いてください(任意))

**Comment by heisannn** [comment]
~~DO NOT SEND SUCH THAT ISSUE~~
pLeAsE sPeCiFy WhAt Is wRoNg
