### ISSUE TITLE
footerの表示設定がtrueであるにもかかわらず、footerが表示されない

### ISSUE THREAD

**Issue by castella-cake** [touhourenren/TJAPlayer3-Develop-ReWrite#50]
footerの表示設定を一切触っていなくても、一部の環境で発生する問題。
発生手順も何もわからないため、原因不明としてマーク。
(From Discord)

**Comment by castella-cake** [comment]
-原因判明-
ConfigにてAVIの設定をオフにすることで解決可能。
恐らくAVIを背景やダンサーの上で描画する仕様だった可能性が高く、footerは最前面に表示されるため非表示にされると推測。

**Comment by Reiya0917milk** [comment]
AVI有効時にダンサーモブフッターを無効にしています
[CStage演奏ドラム画面.cs 469行目]( https://github.com/touhourenren/TJAPlayer3-Develop-ReWrite/blob/master/TJAPlayer3/Stages/07.Game/Taiko/CStage%E6%BC%94%E5%A5%8F%E3%83%89%E3%83%A9%E3%83%A0%E7%94%BB%E9%9D%A2.cs#L469 )

**Comment by touhourenren** [comment]
原因解明に付きClose。
