### ISSUE TITLE
ジャンル説明に使用するフォントにスーラを使用した場合に、行間と座標がおかしくなる

### ISSUE THREAD

**Issue by castella-cake** [touhourenren/TJAPlayer3-Develop-ReWrite#52]
ジャンルの説明に使用するフォントでスーラを使用すると、行間や座標が正しく設定されない。
ジャンル説明に使用されるフォントがＤＦＰ太丸ゴシック前提になっていたことが原因であり、
解消方法なども判明しているためアップデートで解消予定。
(From Discord)

**Comment by touhourenren** [comment]
座標の修正機能、行間の指定機能を実装したためClose。
