### ISSUE TITLE
一度バナパスの読み込みに成功すると、その後もう一度成功した際にSEが流れない

### ISSUE THREAD

**Issue by castella-cake** [touhourenren/TJAPlayer3-Develop-ReWrite#53]
**Describe the bug**
(バグについての説明を書いてください)
タイトル画面でPを押してバナパスの読み込みに成功させた際、もう一度成功させるとSEが流れないバグ。

**To Reproduce**
(バグを引き起こすまでの手順を書いてください)
1. P長押しでバナパスを読み込む。
2. 太鼓の選択でつかわないを選択。
3. もう一度P長押しでバナパスを読み込む。

**Expected behavior**
(バグによって起こる動作)
SEが流れず、そのまま太鼓選択画面へ移動する。

**Comment by touhourenren** [comment]
修正につきClose。
