### ISSUE TITLE
段位でオートを使用した場合に判定がすべて不可になる

### ISSUE THREAD

**Issue by castella-cake** [touhourenren/TJAPlayer3-Develop-ReWrite#62]
そもそもオート用の判定が用意されており、どの判定になろうが必ず「良」になるはず。
原因不明、更に情報が必要としてマーク。

**Comment by touhourenren** [comment]
すみません、ただのコードミスです、先ほどのコードで修正したのでClose。

**Comment by castella-cake** [comment]
修正コミット公開のためクローズ。
