### ISSUE TITLE
BPM値がマイナスの時にフリーズする

### ISSUE THREAD

**Issue by ghost** [touhourenren/TJAPlayer3-Develop-ReWrite#8]
BPM値がマイナスの時にフリーズします。
参考　https://github.com/Mr-Ojii/TJAPlayer3-f/commit/42c3f63aaf91d40b2e35c669e91019d26e413fcd
BPMがマイナスで連打音符中の時に、連打音符が伸びる機能の実装
参考　https://github.com/Mr-Ojii/TJAPlayer3-f/commit/e1043b5529ad4956697bd4557d8962481a18fd2f

**Comment by touhourenren** [comment]
なるほど。
出来れば移植してプルリクエストを送っていただけると幸いです…

**Comment by touhourenren** [comment]
あ、簡単に移植できそうなのでやっておきます。

**Comment by ghost** [comment]
移植ありがとうございます。
